run_test:
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script: 
    - make test

build_image:
  image: docker:20.10.16
  script:
    - docker build -t test .
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"